#pip install -r requirements.txt
#cd chats_project/chats_project/
web: python manage.py runserver

# .env/bin/activate
# pip install -r requirements.txt
# cd socket/
# npm install
# node server.js
# cd ..
# cd chats_project
# python manage.py runserver