# Generated by Django 4.0.4 on 2023-10-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client_password_alter_client_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
