# Generated by Django 4.0.4 on 2023-10-01 23:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type_catalogue', models.TextField()),
                ('amount', models.TextField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'catalogo',
            },
        ),
        migrations.CreateModel(
            name='HistoryConversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField()),
                ('type_messages', models.TextField()),
                ('file', models.TextField(null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usercustomer')),
            ],
            options={
                'db_table': 'historial_conversaciones',
            },
        ),
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField()),
                ('type_messages', models.TextField()),
                ('file', models.TextField(null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usercustomer')),
            ],
            options={
                'db_table': 'conversaciones',
            },
        ),
    ]
