# Generated by Django 4.0.4 on 2023-10-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_conversations_is_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='identify',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historyconversations',
            name='identify',
            field=models.TextField(null=True),
        ),
    ]
