# Generated by Django 4.0.4 on 2023-10-05 12:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_conversations_identify_historyconversations_identify'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomChats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'sala-chats',
            },
        ),
        migrations.AddField(
            model_name='conversations',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chats.roomchats'),
        ),
        migrations.AddField(
            model_name='historyconversations',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chats.roomchats'),
        ),
    ]
