# Generated by Django 4.0.4 on 2023-11-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_roomchats_conversations_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversations',
            name='room',
        ),
        migrations.RemoveField(
            model_name='historyconversations',
            name='room',
        ),
        migrations.DeleteModel(
            name='RoomChats',
        ),
    ]
