# Generated by Django 4.0.4 on 2023-11-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_remove_conversations_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversations',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='historyconversations',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
