# Generated by Django 4.2.7 on 2023-11-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_conversations_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='type_catalogue',
            field=models.TextField(null=True),
        ),
    ]
