# Generated by Django 4.2.7 on 2023-11-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_catalogue_type_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='images',
            field=models.ImageField(null=True, upload_to='../staticfiles/admin/img_catalogue'),
        ),
    ]
