# Generated by Django 4.2.7 on 2023-11-22 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_remove_catalogue_images_catalogue_mages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogue',
            old_name='mages',
            new_name='images',
        ),
    ]
